name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.0'
        setup-python: 'false'
        # mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
    - name: Install python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements_dev.txt
    - name: Install xvfb on macOS
      if: runner.os == 'macOS'
      run: |
        brew install xvfb
    - name: Tests and coverage
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        if [[ "$RUNNER_OS" == "Mac OS X" ]]; then
          xvfb-run -s "-screen 0 1024x768x24" invoke coverage
        else
          invoke coverage
        fi
    - name: Lint
      run: |
        invoke lint
    - name: Coveralls report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
